### ISSUE TITLE
[Bug] Missing floor field in `TiebaPostSpider.parse_totalComment` and `TiebaPostSpider.parse_comment`

### ISSUE THREAD

**Issue by HairlessVillager** [HairlessVillager/minehotspot#7]

**Comment by HairlessVillager** [comment]
@BzcLoveXrn

**Comment by binzc2004** [comment]
parse_totalComment的字段是从json中获取的，但是json中没有二级评论回复的一级评论楼数，能有的信息只有一级评论所对应的帖子id是多少，怎么处理
![image](https://github.com/HairlessVillager/minehotspot/assets/152786339/8ce91ebf-1a01-443d-9969-d0abce50ced4)

**Comment by HairlessVillager** [comment]
那这个暂时放着，写一个TODO

**Comment by binzc2004** [comment]
parse_comment也是一样，找不到所对应的一级评论的楼数，只有id
![image](https://github.com/HairlessVillager/minehotspot/assets/152786339/e501c949-79f1-4694-b570-e353ddc46604)
我给这两个标记为Todo,需要commit嘛,顺便问一问，bilibili我要怎么爬呢，就是需要爬那些字段呢

**Comment by HairlessVillager** [comment]
> 我给这两个标记为Todo,需要commit嘛

是的，你提交吧
