### ISSUE TITLE
Bug Report:  tieba.py

### ISSUE THREAD

**Issue by binzc2004** [HairlessVillager/minehotspot#9]
@HairlessVillager
问题复现：在控制台输入以下命令爬取贴吧，scrapy crawl tiebapost -a pid=8351704896

![image](https://github.com/HairlessVillager/minehotspot/assets/152786339/d1112298-0d1c-4040-b3a2-34de683f4618)

问题描述：

- 在最初版本的TiebaComment里，有title(帖子标题这个字段)，当前版本已经被删除，但是爬虫代码中，仍然有该字段

![image](https://github.com/HairlessVillager/minehotspot/assets/152786339/6ee4d323-c2d9-45c1-a585-dabcac6ae14e)
导致运行爬虫的时候，会报错如下：
![image](https://github.com/HairlessVillager/minehotspot/assets/152786339/0cca5fd1-f07e-42e0-8ba7-b546763edc2d)

- 在目前版本的TiebaComent中，有uname该字段，但是在爬虫代码中，该字段并未处理，结果是uname字段全为none，如下

![image](https://github.com/HairlessVillager/minehotspot/assets/152786339/b5768b74-b400-40a1-ae21-5e7e3a5de904)

**Comment by HairlessVillager** [comment]
对于问题1：

不要修改items.TiebaComment，而是修改爬取的代码。

---

对于问题2：

uid是表示用户的一个整数，uname是用户的昵称。当前版本的处理逻辑是这样的：

https://github.com/HairlessVillager/minehotspot/blob/87eca65f9b738d9e4d6ff9924f91647af42fdefe/minehotspot/src/scrapy/minehotspot/spiders/tieba.py#L138

这里给出大概的修改思路：

```py
uid=user_id, uname=show_nickname
```

如果无法获取字段，设置为`None`即可，必要时可以加注释说明。

---

另外这个issue写的挺好的，除了一个小问题，就是标题没有起到标题的作用，类似的问题我之前也和你说过，下不为例😥

**Comment by binzc2004** [comment]
已修改完善，已提交
